### ISSUE TITLE
Inquiry on Pairwise Comparison Settings

### ISSUE THREAD

**Issue by lzyent** [ZhangLabGT/scDisInFact#1]
Hi,
Congratulations on the recent publication! Your innovative framework for single-cell data integration and condition effect prediction is truly remarkable.
I am interested in understanding whether scDisInFact provides the capability to apply pairwise comparison settings for matched samples within multi-batches, multi-conditions scRNA-seq datasets. Could you please advise if scDisInFact includes options to configure pairwise comparison settings for matched samples?
Thank you for your time!

**Comment by PeterZZQ** [comment]
Hi, thank you for your interest. Can you explain more about the pairwise comparison and the matched samples? Do you mean cells under different conditions are already one-to-one matched?

**Comment by lzyent** [comment]
Exactly, in the provided demo, I didn't find where could allow users to specify the dependence between groups like patient info (having matched samples, like pre-Tx and post-Tx).

**Comment by PeterZZQ** [comment]
Sorry, I'm still a little confused. Did you run some alignment algorithm to match the cells under different groups? Because cell can only be measured once under one condition right? 

If you have two groups of cells with different conditions (like in your example, one under "pre-Tx", and the other under "post-Tx"), then you can directly run scDisInFact without aligning the samples in advance. Just consider the cells are under one batch but two conditions, then you can set the condition and batch label of the cells using the command:

```
data_dict = create_scdisinfact_dataset(counts, meta_cells, condition_key = ["experiment condition"], batch_key = "batch")
```

The `counts` is a merged cell-by-gene count matrix that includes cells of all conditions (pre-Tx and post-Tx), `meta_cells` is a data frame that saves the patient info as you mentioned above. You need to create a meta_cells data frame that stores the information (condition and batch) of each individual cell in your count matrix. In the command above, you specific the column name of the condition in the meta_cells is `experiment condition`, then when you create the meta_cells data frame, you need to make sure that you have that column with the exact name that save the condition information of each cell (pre-Tx or post-Tx). The same goes with the batch column (you need to have a column in meta_cells that save the batch information of cells named `batch`, because all cells are from the same batch, then assign the same batch ID in the column).

**Comment by lzyent** [comment]
Thank you for offering the example, my point is, in meta_cell df, I have another `patient`, indicating that samples before and after treatment are dependent, can I feed this information to the scDisInFact? I think it will make a difference somehow with that infomation.

**Comment by PeterZZQ** [comment]
Ok. So you have two columns in `meta_cell` df that you wish to use, one is `patient`, another is the 
 condition (pre-Tx & post-Tx). For each patient, you have the scRNA-seq data corresponding to both the pre-Tx condition and post-Tx condition, that is what you mean by matched sample right?
 
scDisInFact can be applied to this case:
* If you mainly focus on learning the response to condition (pre-Tx, post-Tx), you can treat `patient` as batches, and pre-Tx, post-Tx as condition.  
* If you wish to learn both the response to condition and the patient specific effect, you can treat both `patient` and pre-Tx & post-Tx as condition, and assume all data are from the same batch (if the batch effect is not obvious).
